import type {
  Tenant,
  User,
  Tasker,
  Booking,
  PartnerApplication,
  CronJobItem,
  ServiceCategory,
  ServiceItem,
  WalletTransaction,
  FinancialSummary,
  TenantSettings,
} from '../types/index.ts';

export const INITIAL_TENANTS: Tenant[] = [
  {
    id: 'tenant-linkkwork',
    code: 'LINKKWORK',
    name: 'Nền tảng LinkkWork (Platform Owner)',
    taxId: '0109999999',
    phone: '1900 6868',
    email: 'hotline@linkkwork.vn',
    city: 'Toàn quốc',
    status: 'ACTIVE',
    plan: 'ENTERPRISE',
    commissionRate: 0,
    isDefault: true,
    taskerCount: 450,
    activeOrderCount: 68,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'tenant-anh-duong',
    code: 'ANH_DUONG',
    name: 'Công ty Vệ Sinh Ánh Dương',
    taxId: '0108882233',
    phone: '0988 123 456',
    email: 'contact@anhduongclean.vn',
    city: 'Hà Nội',
    status: 'ACTIVE',
    plan: 'PRO',
    commissionRate: 15,
    isDefault: false,
    taskerCount: 35,
    activeOrderCount: 12,
    createdAt: '2026-03-15T08:30:00Z',
  },
  {
    id: 'tenant-dien-lanh-sg',
    code: 'DIEN_LANH_SG',
    name: 'Điện Lạnh Sài Gòn Xanh',
    taxId: '0307775566',
    phone: '0909 888 999',
    email: 'admin@dienlanhsg.com',
    city: 'TP. Hồ Chí Minh',
    status: 'PAST_DUE',
    plan: 'BASIC',
    commissionRate: 18,
    isDefault: false,
    taskerCount: 18,
    activeOrderCount: 4,
    createdAt: '2026-05-20T10:00:00Z',
  },
  {
    id: 'tenant-clean-home',
    code: 'CLEAN_HOME',
    name: 'Dịch Vụ Nhà Sạch Hà Nội',
    taxId: '0106661122',
    phone: '0912 334 455',
    email: 'support@nhasachhn.vn',
    city: 'Hà Nội',
    status: 'ACTIVE',
    plan: 'PRO',
    commissionRate: 15,
    isDefault: false,
    taskerCount: 28,
    activeOrderCount: 9,
    createdAt: '2026-06-10T14:20:00Z',
  },
];

export const MOCK_USERS: User[] = [
  {
    id: 'user-super-admin',
    name: 'Nguyễn Văn Minh (Super Admin)',
    email: 'superadmin@linkkwork.vn',
    role: 'SUPER_ADMIN',
    tenantId: 'tenant-linkkwork',
    tenantName: 'Nền tảng LinkkWork',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&h=100&fit=crop&crop=face',
  },
  {
    id: 'user-tenant-anh-duong',
    name: 'Trần Thị Thu Hà (Quản lý Ánh Dương)',
    email: 'admin@anhduong.vn',
    role: 'TENANT_ADMIN',
    tenantId: 'tenant-anh-duong',
    tenantName: 'Công ty Vệ Sinh Ánh Dương',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=100&h=100&fit=crop&crop=face',
  },
  {
    id: 'user-tenant-dien-lanh',
    name: 'Lê Hoàng Nam (Quản lý Điện Lạnh SG)',
    email: 'admin@dienlanhsg.com',
    role: 'TENANT_ADMIN',
    tenantId: 'tenant-dien-lanh-sg',
    tenantName: 'Điện Lạnh Sài Gòn Xanh',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=face',
  },
];

export const INITIAL_TASKERS: Tasker[] = [
  // Taskers of Tenant Ánh Dương
  {
    id: 'tsk-ad-01',
    code: 'TSK-AD-01',
    name: 'Nguyễn Thị Lan',
    phone: '0971 112 233',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&h=100&fit=crop&crop=face',
    tenantId: 'tenant-anh-duong',
    tenantName: 'Công ty Vệ Sinh Ánh Dương',
    rating: 4.95,
    ratingScore: 4.95,
    completedJobs: 342,
    isOnline: true,
    walletBalance: 850000,
    depositBalance: 500000,
    softHoldBalance: 60000,
    currentStatus: 'IDLE',
    kycVerified: true,
    skills: ['Dọn dẹp nhà theo giờ', 'Ủi quần áo', 'Nấu ăn gia đình'],
  },
  {
    id: 'tsk-ad-02',
    code: 'TSK-AD-02',
    name: 'Vũ Thị Mai',
    phone: '0972 223 344',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=100&h=100&fit=crop&crop=face',
    tenantId: 'tenant-anh-duong',
    tenantName: 'Công ty Vệ Sinh Ánh Dương',
    rating: 4.88,
    ratingScore: 4.88,
    completedJobs: 215,
    isOnline: true,
    walletBalance: 420000,
    depositBalance: 300000,
    softHoldBalance: 0,
    currentStatus: 'ARRIVING',
    kycVerified: true,
    skills: ['Dọn dẹp nhà theo giờ', 'Tổng vệ sinh sau xây dựng'],
  },
  {
    id: 'tsk-ad-03',
    code: 'TSK-AD-03',
    name: 'Đặng Kim Chi',
    phone: '0973 334 455',
    avatarUrl: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=100&h=100&fit=crop&crop=face',
    tenantId: 'tenant-anh-duong',
    tenantName: 'Công ty Vệ Sinh Ánh Dương',
    rating: 4.92,
    ratingScore: 4.92,
    completedJobs: 178,
    isOnline: false,
    walletBalance: 310000,
    depositBalance: 250000,
    softHoldBalance: 0,
    currentStatus: 'IDLE',
    kycVerified: true,
    skills: ['Dọn dẹp nhà theo giờ', 'Giặt sofa nệm'],
  },
  // Taskers of Tenant Điện Lạnh SG
  {
    id: 'tsk-dl-01',
    code: 'TSK-DL-01',
    name: 'Trần Văn Hùng (Thợ Điện Lạnh)',
    phone: '0918 445 566',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop&crop=face',
    tenantId: 'tenant-dien-lanh-sg',
    tenantName: 'Điện Lạnh Sài Gòn Xanh',
    rating: 4.98,
    ratingScore: 4.98,
    completedJobs: 480,
    isOnline: true,
    walletBalance: 1250000,
    depositBalance: 800000,
    softHoldBalance: 90000,
    currentStatus: 'IN_PROGRESS',
    kycVerified: true,
    skills: ['Vệ sinh máy lạnh', 'Sửa chữa điện lạnh', 'Bảo dưỡng điều hòa'],
  },
  // Taskers of LinkkWork Platform (Freelance)
  {
    id: 'tsk-lw-01',
    code: 'TSK-LW-01',
    name: 'Hoàng Kim Oanh (Tasker Tự Do)',
    phone: '0989 999 111',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&h=100&fit=crop&crop=face',
    tenantId: 'tenant-linkkwork',
    tenantName: 'Nền tảng LinkkWork (Platform)',
    rating: 4.91,
    ratingScore: 4.91,
    completedJobs: 620,
    isOnline: true,
    walletBalance: 590000,
    depositBalance: 400000,
    softHoldBalance: 45000,
    currentStatus: 'IDLE',
    kycVerified: true,
    skills: ['Dọn dẹp nhà theo giờ', 'Trông trẻ', 'Chăm sóc người già'],
  },
];

export const INITIAL_BOOKINGS: Booking[] = [
  {
    id: 'bk-101',
    code: 'BK-2026-101',
    originTenantId: 'tenant-anh-duong',
    servicingTenantId: 'tenant-anh-duong',
    servicingTenantName: 'Công ty Vệ Sinh Ánh Dương',
    customerName: 'Chị Hoàng Phương Dung',
    customerPhone: '0903 111 222',
    addressText: 'P.1204 Tòa Park 3, Vinhomes Times City, Hai Bà Trưng, Hà Nội',
    serviceId: 'srv-hourly',
    serviceName: 'Dọn dẹp nhà theo giờ (3 giờ)',
    pricingType: 'HOURLY',
    durationHours: 3,
    scheduledAt: '2026-10-05T14:30:00Z',
    totalAmount: 290000,
    status: 'IN_PROGRESS',
    assignedTaskerId: 'tsk-ad-01',
    assignedTaskerName: 'Nguyễn Thị Lan',
    assignedTaskerPhone: '0971 112 233',
    createdAt: '2026-10-05T08:15:00Z',
  },
  {
    id: 'bk-102',
    code: 'BK-2026-102',
    originTenantId: 'tenant-anh-duong',
    servicingTenantId: 'tenant-anh-duong',
    servicingTenantName: 'Công ty Vệ Sinh Ánh Dương',
    customerName: 'Anh Phạm Đức Minh',
    customerPhone: '0912 444 777',
    addressText: 'Số 48 Ngõ 165 Cầu Giấy, Cầu Giấy, Hà Nội',
    serviceId: 'srv-hourly',
    serviceName: 'Dọn dẹp nhà theo giờ + Ủi đồ (4 giờ)',
    pricingType: 'HOURLY',
    durationHours: 4,
    scheduledAt: '2026-10-05T17:00:00Z',
    totalAmount: 380000,
    status: 'PENDING_DISPATCH',
    assignedTaskerId: null,
    assignedTaskerName: null,
    assignedTaskerPhone: null,
    createdAt: '2026-10-05T11:20:00Z',
  },
  {
    id: 'bk-103',
    code: 'BK-2026-103',
    originTenantId: 'tenant-dien-lanh-sg',
    servicingTenantId: 'tenant-dien-lanh-sg',
    servicingTenantName: 'Điện Lạnh Sài Gòn Xanh',
    customerName: 'Chị Nguyễn Thu Thảo',
    customerPhone: '0938 555 888',
    addressText: '88 Đường Song Hành, Thảo Điền, TP. Thủ Đức, TP.HCM',
    serviceId: 'srv-ac',
    serviceName: 'Vệ sinh máy lạnh treo tường (2 máy)',
    pricingType: 'PER_UNIT',
    scheduledAt: '2026-10-05T15:00:00Z',
    totalAmount: 400000,
    status: 'ASSIGNED',
    assignedTaskerId: 'tsk-dl-01',
    assignedTaskerName: 'Trần Văn Hùng',
    assignedTaskerPhone: '0918 445 566',
    createdAt: '2026-10-05T09:40:00Z',
  },
  {
    id: 'bk-104',
    code: 'BK-2026-104',
    originTenantId: 'tenant-linkkwork',
    servicingTenantId: 'tenant-linkkwork',
    servicingTenantName: 'Nền tảng LinkkWork (Platform)',
    customerName: 'Anh Vũ Tuấn Hưng',
    customerPhone: '0908 777 666',
    addressText: 'Villa 15 Khu Đô Thị Sala, Quận 2, TP.HCM',
    serviceId: 'srv-deepclean',
    serviceName: 'Tổng vệ sinh chuyên sâu biệt thự (Bidding)',
    pricingType: 'BIDDING',
    scheduledAt: '2026-10-06T08:00:00Z',
    totalAmount: 3500000,
    status: 'COMPLETED',
    assignedTaskerId: 'tsk-lw-01',
    assignedTaskerName: 'Hoàng Kim Oanh',
    assignedTaskerPhone: '0989 999 111',
    createdAt: '2026-10-04T10:00:00Z',
  },
];

export const INITIAL_PARTNER_APPLICATIONS: PartnerApplication[] = [
  {
    id: 'app-01',
    businessName: 'Công ty TNHH Dịch Vụ Nhà Sạch An Phát',
    taxId: '0401928374',
    contactName: 'Lê Văn An',
    contactPhone: '0935 123 789',
    contactEmail: 'contact@anphatclean.com',
    city: 'Đà Nẵng',
    services: ['Dọn dẹp nhà theo giờ', 'Vệ sinh máy lạnh', 'Giặt sofa nệm'],
    selectedServices: ['Dọn dẹp nhà theo giờ', 'Vệ sinh máy lạnh', 'Giặt sofa nệm'],
    licenseDocUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=800',
    status: 'SUBMITTED',
    createdAt: '2026-10-05T09:12:00Z',
  },
  {
    id: 'app-02',
    businessName: 'Công ty Cổ Phần Cơ Điện Lạnh Miền Tây',
    taxId: '1802345678',
    contactName: 'Nguyễn Hữu Tài',
    contactPhone: '0949 888 777',
    contactEmail: 'tainguyen@mientaymep.vn',
    city: 'Cần Thơ',
    services: ['Vệ sinh máy lạnh', 'Bảo dưỡng điện lạnh'],
    selectedServices: ['Vệ sinh máy lạnh', 'Bảo dưỡng điện lạnh'],
    licenseDocUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=800',
    status: 'UNDER_REVIEW',
    createdAt: '2026-10-04T16:30:00Z',
  },
];

export const INITIAL_CRON_JOBS: CronJobItem[] = [
  {
    jobName: 'recurring-booking-generator',
    description: 'Tự động quét hợp đồng lặp lại và sinh đơn con trước 48 giờ',
    cronExpression: '0 0 * * *',
    isEnabled: true,
    lastRunAt: '2026-10-05T00:00:02Z',
    lastStatus: 'SUCCESS',
    durationMs: 840,
    successCount: 142,
    failCount: 0,
    params: { advanceHours: 48, favoriteLockHours: 6 },
  },
  {
    jobName: 'emergency-redispatch-watchdog',
    description: 'Quét và kích hoạt thưởng nóng cứu đơn khi thợ no-show hoặc sát giờ ca làm',
    cronExpression: '*/5 * * * *',
    isEnabled: true,
    lastRunAt: '2026-10-05T17:45:00Z',
    lastStatus: 'SUCCESS',
    durationMs: 310,
    successCount: 3,
    failCount: 0,
    params: { urgentThresholdMinutes: 60, bonusAmount: 50000 },
  },
  {
    jobName: 'auto-complete-booking',
    description: 'Tự động nghiệm thu và cấn trừ hoa hồng sau 4 giờ hoàn tất',
    cronExpression: '*/15 * * * *',
    isEnabled: true,
    lastRunAt: '2026-10-05T17:30:00Z',
    lastStatus: 'SUCCESS',
    durationMs: 420,
    successCount: 28,
    failCount: 0,
    params: { autoCompleteHours: 4 },
  },
  {
    jobName: 'tenant-subscription-guard',
    description: 'Kiểm tra hạn gói cước của Tenant và kích hoạt ân hạn Grace Period',
    cronExpression: '0 6 * * *',
    isEnabled: true,
    lastRunAt: '2026-10-05T06:00:05Z',
    lastStatus: 'SUCCESS',
    durationMs: 250,
    successCount: 1,
    failCount: 0,
    params: { gracePeriodDays: 5 },
  },
  {
    jobName: 'hot-cold-gps-archiver',
    description: 'Lưu trữ tọa độ GPS từ Redis Ingestion sang Cold Database TimescaleDB',
    cronExpression: '*/10 * * * *',
    isEnabled: false,
    lastRunAt: '2026-10-05T16:20:00Z',
    lastStatus: 'PAUSED',
    durationMs: 1250,
    successCount: 12400,
    failCount: 0,
    params: { batchSize: 500 },
  },
];

export const INITIAL_SERVICE_CATEGORIES: ServiceCategory[] = [
  {
    id: 'cat-cleaning',
    name: 'Dọn dẹp nhà cửa',
    slug: 'don-dep-nha-cua',
    description: 'Dịch vụ giúp việc nhà theo giờ, tổng vệ sinh và ủi đồ',
    iconName: 'Sparkles',
    displayOrder: 1,
  },
  {
    id: 'cat-ac-repair',
    name: 'Điện lạnh & Điện gia dụng',
    slug: 'dien-lanh-gia-dung',
    description: 'Vệ sinh, sửa chữa, bảo dưỡng điều hòa máy lạnh và tủ lạnh',
    iconName: 'AirVent',
    displayOrder: 2,
  },
  {
    id: 'cat-laundry',
    name: 'Giặt ủi & Nệm thảm sofa',
    slug: 'giat-ui-nem-sofa',
    description: 'Giặt khô, sấy hơi nước nóng diệt khuẩn sofa, rèm cửa, đệm cao su',
    iconName: 'Shirt',
    displayOrder: 3,
  },
  {
    id: 'cat-cooking',
    name: 'Nấu ăn & Chăm sóc gia đình',
    slug: 'nau-an-cham-soc',
    description: 'Đầu bếp gia đình theo món, nấu tiệc và chăm sóc người cao tuổi',
    iconName: 'UtensilsCrossed',
    displayOrder: 4,
  },
  {
    id: 'cat-handyman',
    name: 'Sửa chữa điện nước khẩn cấp',
    slug: 'sua-chua-dien-nuoc',
    description: 'Thợ lành nghề xử lý sự cố chập điện, rò rỉ ống nước, thay khóa',
    iconName: 'Wrench',
    displayOrder: 5,
  },
];

export const INITIAL_SERVICES: ServiceItem[] = [
  {
    id: 'srv-hourly-cleaning',
    categoryId: 'cat-cleaning',
    categoryName: 'Dọn dẹp nhà cửa',
    name: 'Dọn dẹp nhà theo giờ',
    slug: 'don-dep-nha-theo-gio',
    description: 'Lau dọn phòng khách, phòng ngủ, cọ rửa toilet, dọn bếp và quét nhà',
    pricingModel: 'HOURLY',
    basePrice: 80000,
    unitLabel: 'giờ',
    minHours: 2,
    isActive: true,
    addons: [
      { id: 'add-01', name: 'Mang theo bộ dụng cụ chuyên nghiệp', price: 30000, description: 'Cây lau xoay 360, khăn vi sợi, chổi' },
      { id: 'add-02', name: 'Ủi quần áo (tối đa 10 áo/quần)', price: 40000, description: 'Yêu cầu có sẵn bàn ủi tại nhà' },
      { id: 'add-03', name: 'Nước tẩy rửa sinh học cao cấp Eco', price: 25000, description: 'An toàn cho trẻ sơ sinh và thú cưng' },
    ],
    createdAt: '2026-01-10T08:00:00Z',
  },
  {
    id: 'srv-ac-cleaning',
    categoryId: 'cat-ac-repair',
    categoryName: 'Điện lạnh & Điện gia dụng',
    name: 'Vệ sinh máy lạnh treo tường (1.0 - 2.5 HP)',
    slug: 've-sinh-may-lanh-treo-tuong',
    description: 'Tháo vỏ, xịt rửa dàn lạnh, dàn nóng, thông ống thoát nước và đo gas',
    pricingModel: 'PER_UNIT',
    basePrice: 150000,
    unitLabel: 'bộ máy',
    isActive: true,
    addons: [
      { id: 'add-ac-01', name: 'Châm thêm Gas R32 / R410A tiêu chuẩn', price: 120000, description: 'Đảm bảo áp suất làm lạnh sâu' },
      { id: 'add-ac-02', name: 'Xịt khử khuẩn dàn lạnh bằng ion bạc', price: 50000, description: 'Diệt nấm mốc và mùi hôi ẩm ướt' },
    ],
    createdAt: '2026-01-15T08:00:00Z',
  },
  {
    id: 'srv-deep-clean',
    categoryId: 'cat-cleaning',
    categoryName: 'Dọn dẹp nhà cửa',
    name: 'Tổng vệ sinh nhà sau xây dựng / Căn hộ mới',
    slug: 'tong-ve-sinh-nha-sau-xay-dung',
    description: 'Đội ngũ thợ 3-5 người kèm máy hút bụi công nghiệp đánh sàn',
    pricingModel: 'BIDDING',
    basePrice: 0,
    unitLabel: 'công trình',
    isActive: true,
    addons: [
      { id: 'add-deep-01', name: 'Đánh bóng sàn đá Marble / Granite', price: 500000, description: 'Hóa chất ngoại nhập phục hồi độ bóng' },
      { id: 'add-deep-02', name: 'Lau kính mặt ngoài nhà cao tầng', price: 350000, description: 'Đầy đủ đai bảo hộ an toàn lao động' },
    ],
    createdAt: '2026-01-20T08:00:00Z',
  },
  {
    id: 'srv-sofa-clean',
    categoryId: 'cat-laundry',
    categoryName: 'Giặt ủi & Nệm thảm sofa',
    name: 'Giặt ghế Sofa vải / nỉ / da phòng khách',
    slug: 'giat-ghe-sofa-phong-khach',
    description: 'Phun hút nước nóng diệt khuẩn, đánh sạch vết ố cà phê và khử mùi hôi',
    pricingModel: 'PER_UNIT',
    basePrice: 350000,
    unitLabel: 'bộ sofa',
    isActive: true,
    addons: [
      { id: 'add-sofa-01', name: 'Sấy khô thần tốc bằng quạt nhiệt UV', price: 80000, description: 'Khô ngay sau 45 phút, sẵn sàng sử dụng' },
      { id: 'add-sofa-02', name: 'Phủ nano chống thấm nước bề mặt da/vải', price: 100000, description: 'Ngăn vết bẩn thấm sâu vào mút đệm' },
    ],
    createdAt: '2026-02-01T08:00:00Z',
  },
  {
    id: 'srv-home-cooking',
    categoryId: 'cat-cooking',
    categoryName: 'Nấu ăn & Chăm sóc gia đình',
    name: 'Nấu ăn gia đình chuẩn vị cơm nhà',
    slug: 'nau-an-gia-dinh',
    description: 'Nấu mâm cơm 3-4 món theo khẩu vị gia đình (Bắc - Trung - Nam), dọn rửa sau ăn',
    pricingModel: 'HOURLY',
    basePrice: 90000,
    unitLabel: 'giờ',
    minHours: 2,
    isActive: true,
    addons: [
      { id: 'add-cook-01', name: 'Đi chợ chọn thực phẩm tươi sống', price: 50000, description: 'Mua thực phẩm theo ngân sách gia đình cấp' },
      { id: 'add-cook-02', name: 'Nấu thêm món tráng miệng / chè thanh nhiệt', price: 40000, description: 'Nguyên liệu do chủ nhà chuẩn bị' },
    ],
    createdAt: '2026-02-15T08:00:00Z',
  },
];

export const INITIAL_FINANCIAL_TRANSACTIONS: WalletTransaction[] = [
  {
    id: 'tx-001',
    code: 'TX-2026-901',
    tenantId: 'tenant-anh-duong',
    tenantName: 'Công ty Vệ Sinh Ánh Dương',
    taskerId: 'tsk-ad-01',
    taskerName: 'Nguyễn Thị Lan',
    bookingCode: 'BK-2026-101',
    type: 'SOFT_HOLD',
    amount: 60000,
    direction: 'OUT',
    balanceBefore: 850000,
    balanceAfter: 790000,
    status: 'COMPLETED',
    sourceType: 'TASKER',
    sourceId: 'tsk-ad-01',
    sourceName: 'Nguyễn Thị Lan',
    targetType: 'PLATFORM',
    targetName: 'Hệ thống LinkkWork',
    paymentMethod: 'WALLET',
    notes: 'Tạm khóa cọc ký quỹ nhận đơn [BK-2026-101]',
    createdAt: '2026-10-05T08:16:00Z',
  },
  {
    id: 'tx-002',
    code: 'TX-2026-902',
    tenantId: 'tenant-dien-lanh-sg',
    tenantName: 'Điện Lạnh Sài Gòn Xanh',
    taskerId: 'tsk-dl-01',
    taskerName: 'Trần Văn Hùng',
    bookingCode: 'BK-2026-103',
    type: 'COMMISSION_FEE',
    amount: 67500,
    direction: 'OUT',
    balanceBefore: 1250000,
    balanceAfter: 1182500,
    status: 'COMPLETED',
    sourceType: 'TASKER',
    sourceId: 'tsk-dl-01',
    sourceName: 'Trần Văn Hùng',
    targetType: 'TENANT',
    targetId: 'tenant-dien-lanh-sg',
    targetName: 'Điện Lạnh Sài Gòn Xanh',
    paymentMethod: 'WALLET',
    notes: 'Thu hoa hồng sàn 15% cho đơn [BK-2026-103] (450.000 đ)',
    createdAt: '2026-10-05T14:40:00Z',
  },
  {
    id: 'tx-003',
    code: 'TX-2026-903',
    tenantId: 'tenant-anh-duong',
    tenantName: 'Công ty Vệ Sinh Ánh Dương',
    taskerId: 'tsk-ad-02',
    taskerName: 'Vũ Thị Mai',
    type: 'TOP_UP_DEPOSIT',
    amount: 500000,
    direction: 'IN',
    balanceBefore: 350000,
    balanceAfter: 850000,
    status: 'COMPLETED',
    sourceType: 'TASKER',
    sourceId: 'tsk-ad-02',
    sourceName: 'Vũ Thị Mai',
    targetType: 'WALLET',
    targetName: 'Ví ký quỹ thợ',
    paymentMethod: 'BANK_TRANSFER',
    notes: 'Nạp tiền ví ký quỹ qua chuyển khoản ngân hàng Vietcombank',
    createdAt: '2026-10-05T10:15:00Z',
  },
  {
    id: 'tx-004',
    code: 'TX-2026-904',
    tenantId: 'tenant-dien-lanh-sg',
    tenantName: 'Điện Lạnh Sài Gòn Xanh',
    type: 'SUBSCRIPTION_FEE',
    amount: 2500000,
    direction: 'OUT',
    balanceBefore: 17900000,
    balanceAfter: 15400000,
    status: 'COMPLETED',
    sourceType: 'TENANT',
    sourceId: 'tenant-dien-lanh-sg',
    sourceName: 'Điện Lạnh Sài Gòn Xanh',
    targetType: 'PLATFORM',
    targetName: 'Nền tảng LinkkWork',
    paymentMethod: 'BANK_TRANSFER',
    notes: 'Thanh toán gói cước Subscription SaaS tháng 10/2026 (Gói PRO)',
    createdAt: '2026-10-01T00:05:00Z',
  },
  {
    id: 'tx-005',
    code: 'TX-2026-905',
    tenantId: 'tenant-anh-duong',
    tenantName: 'Công ty Vệ Sinh Ánh Dương',
    bookingCode: 'BK-2026-098',
    type: 'ORDER_PAYOUT',
    amount: 320000,
    direction: 'IN',
    balanceBefore: 780000,
    balanceAfter: 8120000,
    status: 'COMPLETED',
    sourceType: 'CUSTOMER',
    sourceName: 'Khách hàng',
    targetType: 'TENANT',
    targetId: 'tenant-anh-duong',
    targetName: 'Công ty Vệ Sinh Ánh Dương',
    paymentMethod: 'CASH',
    notes: 'Quyết toán tiền công sau khi khách hàng nghiệm thu đơn [BK-2026-098]',
    createdAt: '2026-10-04T18:30:00Z',
  },
];

export const INITIAL_FINANCIAL_SUMMARY: FinancialSummary = {
  grossServiceVolume: 184500000,
  platformCommissionEarned: 27675000,
  tenantNetRevenue: 156825000,
  totalDepositHeld: 48500000,
  pendingSettlementsCount: 14,
};

export const INITIAL_TENANT_SETTINGS: Record<string, TenantSettings> = {
  'tenant-linkkwork': {
    tenantId: 'tenant-linkkwork',
    hotline: '1900 6868',
    supportEmail: 'hotline@linkkwork.vn',
    businessAddress: 'Tòa nhà LinkkWork Tower, Số 1 Đường Sáng Tạo, Quận 1, TP.HCM',
    autoDispatchEnabled: true,
    maxRadiusKm: 15,
    defaultCommissionRate: 15,
    workingHours: { start: '06:00', end: '22:00' },
  },
  'tenant-anh-duong': {
    tenantId: 'tenant-anh-duong',
    hotline: '0988 123 456',
    supportEmail: 'cskh@anhduongclean.vn',
    businessAddress: 'Tầng 4 Tòa nhà Detech, Số 8 Tôn Thất Thuyết, Mỹ Đình, Hà Nội',
    autoDispatchEnabled: true,
    maxRadiusKm: 10,
    defaultCommissionRate: 15,
    workingHours: { start: '07:00', end: '21:00' },
  },
  'tenant-dien-lanh-sg': {
    tenantId: 'tenant-dien-lanh-sg',
    hotline: '0909 778 899',
    supportEmail: 'hotline@dienlanhsaigonxanh.com',
    businessAddress: 'Số 120 Đường Hoàng Văn Thụ, Phường 9, Quận Phú Nhuận, TP.HCM',
    autoDispatchEnabled: false,
    maxRadiusKm: 12,
    defaultCommissionRate: 15,
    workingHours: { start: '07:30', end: '19:30' },
  },
};
