/**
 * Booking lifecycle status machine matching LinkkWork & bTaskee operational models
 */
export enum BookingStatus {
  DRAFT = 'DRAFT',
  PENDING_DISPATCH = 'PENDING_DISPATCH',
  OFFERED_TO_FAVORITE = 'OFFERED_TO_FAVORITE',
  BROADCASTING = 'BROADCASTING',
  ASSIGNED = 'ASSIGNED',
  ARRIVING = 'ARRIVING',
  IN_PROGRESS = 'IN_PROGRESS',
  PENDING_ACCEPTANCE = 'PENDING_ACCEPTANCE',
  COMPLETED = 'COMPLETED',
  REVIEWED = 'REVIEWED',
  CANCELLED = 'CANCELLED',
  EMERGENCY_REDISPATCH = 'EMERGENCY_REDISPATCH',
  DISPATCH_FAILED = 'DISPATCH_FAILED',
}
